import { ImageResponse } from "next/og";
import type { NextRequest } from "next/server";

// Social cards for the pre-launch content run, rendered from HTML rather than generated by
// an image model. Text is the entire content of these posts - a quote, an idea, a book
// title - and image models still mangle text: warped letters, invented spellings, a
// different look every run. Rendering from markup gives exact typography, the product's own
// palette, and a card that is identical on day 1 and day 60, which is what makes a feed look
// like someone runs it.
//
// GET /api/card?layout=idea&title=...&body=...&book=...&author=...&tag=...
// Sizes: 1080x1350 (Instagram portrait, the default) or ?size=square.

export const runtime = "edge";

const INK = "#121713";
const PAPER = "#f6f7f2";
const GREEN_DEEP = "#18392d";
const GREEN = "#9acfb1";
const MUTED = "#646b66";

function Wordmark({ tone = "ink" }: { tone?: "ink" | "paper" }) {
  const color = tone === "ink" ? INK : PAPER;
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
      <div
        style={{
          display: "flex",
          width: 40,
          height: 40,
          borderRadius: 10,
          border: `2px solid ${color}`
        }}
      />
      <div style={{ color, fontSize: 30, fontWeight: 600, letterSpacing: "-0.02em" }}>
        BookSphere
      </div>
    </div>
  );
}

export async function GET(request: NextRequest) {
  const q = request.nextUrl.searchParams;
  const layout = q.get("layout") || "idea";
  const title = q.get("title") || "";
  const body = q.get("body") || "";
  const book = q.get("book") || "";
  const author = q.get("author") || "";
  const tag = q.get("tag") || "";
  const square = q.get("size") === "square";

  const width = 1080;
  const height = square ? 1080 : 1350;

  // Long headlines get a smaller size rather than an overflowing card. Three steps is
  // enough: past ~110 characters the copy is too long for a social card regardless.
  const titleSize = title.length > 110 ? 62 : title.length > 70 ? 74 : 88;

  const dark = layout === "limit";
  const bg = dark ? GREEN_DEEP : PAPER;
  const fg = dark ? PAPER : INK;
  const sub = dark ? "rgba(246,247,242,0.72)" : MUTED;

  return new ImageResponse(
    (
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          width: "100%",
          height: "100%",
          backgroundColor: bg,
          padding: 72,
          fontFamily: "sans-serif"
        }}
      >
        <div style={{ display: "flex", flexDirection: "column" }}>
          <Wordmark tone={dark ? "paper" : "ink"} />
          {tag ? (
            <div
              style={{
                display: "flex",
                marginTop: 44,
                color: dark ? GREEN : MUTED,
                fontSize: 24,
                fontWeight: 600,
                letterSpacing: "0.16em",
                textTransform: "uppercase"
              }}
            >
              {tag}
            </div>
          ) : null}
        </div>

        <div style={{ display: "flex", flexDirection: "column" }}>
          <div
            style={{
              display: "flex",
              color: fg,
              fontSize: titleSize,
              fontWeight: 400,
              lineHeight: 1.08,
              letterSpacing: "-0.03em"
            }}
          >
            {title}
          </div>

          {body ? (
            <div
              style={{
                display: "flex",
                marginTop: 34,
                color: sub,
                fontSize: 32,
                lineHeight: 1.45,
                maxWidth: 880
              }}
            >
              {body}
            </div>
          ) : null}
        </div>

        <div
          style={{
            display: "flex",
            alignItems: "flex-end",
            justifyContent: "space-between",
            borderTop: `1px solid ${dark ? "rgba(246,247,242,0.22)" : "rgba(18,23,19,0.14)"}`,
            paddingTop: 30
          }}
        >
          <div style={{ display: "flex", flexDirection: "column" }}>
            {book ? (
              <div style={{ display: "flex", color: fg, fontSize: 28, fontWeight: 500 }}>{book}</div>
            ) : null}
            {author ? (
              <div style={{ display: "flex", marginTop: 6, color: sub, fontSize: 24 }}>{author}</div>
            ) : null}
          </div>
          <div style={{ display: "flex", color: sub, fontSize: 22 }}>booksphere</div>
        </div>
      </div>
    ),
    { width, height }
  );
}
