-- The catalog lives in src/lib/data.ts and the community lives in Postgres, and
-- until now the only thing connecting them was a fuzzy match on book title AND
-- author. Author strings drift ("Peter Thiel" vs "Peter Thiel and Blake Masters")
-- and that silently stranded five books: no saves, no recommendations, no
-- discussions, no way to even read existing ones.
--
-- Give both sides the same explicit key. The app already derives a stable slug
-- from the title (slugify in src/lib/utils.ts) and uses it as the book's id in
-- every URL, so the slug is the natural contract.
--
-- The values below are generated from the catalog itself rather than
-- reimplemented in SQL, so they match the application byte for byte. Titles are
-- unique on both sides, which makes this one-time title match safe; after it,
-- nothing depends on title or author matching ever again.

alter table public.books add column if not exists slug text;

update public.books set slug = 'atomic-habits' where slug is null and title = 'Atomic Habits';
update public.books set slug = 'the-psychology-of-money' where slug is null and title = 'The Psychology of Money';
update public.books set slug = 'deep-work' where slug is null and title = 'Deep Work';
update public.books set slug = 'zero-to-one' where slug is null and title = 'Zero to One';
update public.books set slug = 'thinking-fast-and-slow' where slug is null and title = 'Thinking, Fast and Slow';
update public.books set slug = 'good-to-great' where slug is null and title = 'Good to Great';
update public.books set slug = 'meditations' where slug is null and title = 'Meditations';
update public.books set slug = 'sapiens' where slug is null and title = 'Sapiens';
update public.books set slug = 'never-split-the-difference' where slug is null and title = 'Never Split the Difference';
update public.books set slug = 'outlive' where slug is null and title = 'Outlive';
update public.books set slug = 'the-innovator-s-dilemma' where slug is null and title = 'The Innovator''s Dilemma';
update public.books set slug = 'high-output-management' where slug is null and title = 'High Output Management';
update public.books set slug = 'the-effective-executive' where slug is null and title = 'The Effective Executive';
update public.books set slug = 'crossing-the-chasm' where slug is null and title = 'Crossing the Chasm';
update public.books set slug = 'blue-ocean-strategy' where slug is null and title = 'Blue Ocean Strategy';
update public.books set slug = 'the-lean-startup' where slug is null and title = 'The Lean Startup';
update public.books set slug = 'built-to-last' where slug is null and title = 'Built to Last';
update public.books set slug = 'measure-what-matters' where slug is null and title = 'Measure What Matters';
update public.books set slug = 'rework' where slug is null and title = 'Rework';
update public.books set slug = 'the-intelligent-investor' where slug is null and title = 'The Intelligent Investor';
update public.books set slug = 'a-random-walk-down-wall-street' where slug is null and title = 'A Random Walk Down Wall Street';
update public.books set slug = 'the-millionaire-next-door' where slug is null and title = 'The Millionaire Next Door';
update public.books set slug = 'your-money-or-your-life' where slug is null and title = 'Your Money or Your Life';
update public.books set slug = 'the-richest-man-in-babylon' where slug is null and title = 'The Richest Man in Babylon';
update public.books set slug = 'the-little-book-of-common-sense-investing' where slug is null and title = 'The Little Book of Common Sense Investing';
update public.books set slug = 'common-stocks-and-uncommon-profits' where slug is null and title = 'Common Stocks and Uncommon Profits';
update public.books set slug = 'fooled-by-randomness' where slug is null and title = 'Fooled by Randomness';
update public.books set slug = 'the-simple-path-to-wealth' where slug is null and title = 'The Simple Path to Wealth';
update public.books set slug = 'one-up-on-wall-street' where slug is null and title = 'One Up On Wall Street';
update public.books set slug = 'security-analysis' where slug is null and title = 'Security Analysis';
update public.books set slug = 'the-most-important-thing' where slug is null and title = 'The Most Important Thing';
update public.books set slug = 'the-essays-of-warren-buffett' where slug is null and title = 'The Essays of Warren Buffett';
update public.books set slug = 'reminiscences-of-a-stock-operator' where slug is null and title = 'Reminiscences of a Stock Operator';
update public.books set slug = 'market-wizards' where slug is null and title = 'Market Wizards';
update public.books set slug = 'the-dhandho-investor' where slug is null and title = 'The Dhandho Investor';
update public.books set slug = 'the-warren-buffett-way' where slug is null and title = 'The Warren Buffett Way';
update public.books set slug = 'mindset' where slug is null and title = 'Mindset';
update public.books set slug = 'the-7-habits-of-highly-effective-people' where slug is null and title = 'The 7 Habits of Highly Effective People';
update public.books set slug = 'essentialism' where slug is null and title = 'Essentialism';
update public.books set slug = 'the-war-of-art' where slug is null and title = 'The War of Art';
update public.books set slug = 'the-obstacle-is-the-way' where slug is null and title = 'The Obstacle Is the Way';
update public.books set slug = 'can-t-hurt-me' where slug is null and title = 'Can''t Hurt Me';
update public.books set slug = 'make-your-bed' where slug is null and title = 'Make Your Bed';
update public.books set slug = 'man-s-search-for-meaning' where slug is null and title = 'Man''s Search for Meaning';
update public.books set slug = 'how-to-win-friends-and-influence-people' where slug is null and title = 'How to Win Friends and Influence People';
update public.books set slug = 'crucial-conversations' where slug is null and title = 'Crucial Conversations';
update public.books set slug = 'nonviolent-communication' where slug is null and title = 'Nonviolent Communication';
update public.books set slug = 'made-to-stick' where slug is null and title = 'Made to Stick';
update public.books set slug = 'influence' where slug is null and title = 'Influence';
update public.books set slug = 'talk-like-ted' where slug is null and title = 'Talk Like TED';
update public.books set slug = 'difficult-conversations' where slug is null and title = 'Difficult Conversations';
update public.books set slug = 'on-writing-well' where slug is null and title = 'On Writing Well';
update public.books set slug = 'everybody-writes' where slug is null and title = 'Everybody Writes';
update public.books set slug = 'predictably-irrational' where slug is null and title = 'Predictably Irrational';
update public.books set slug = 'flow' where slug is null and title = 'Flow';
update public.books set slug = 'the-power-of-habit' where slug is null and title = 'The Power of Habit';
update public.books set slug = 'grit' where slug is null and title = 'Grit';
update public.books set slug = 'stumbling-on-happiness' where slug is null and title = 'Stumbling on Happiness';
update public.books set slug = 'the-righteous-mind' where slug is null and title = 'The Righteous Mind';
update public.books set slug = 'quiet' where slug is null and title = 'Quiet';
update public.books set slug = 'drive' where slug is null and title = 'Drive';
update public.books set slug = 'the-mom-test' where slug is null and title = 'The Mom Test';
update public.books set slug = 'traction' where slug is null and title = 'Traction';
update public.books set slug = 'inspired' where slug is null and title = 'Inspired';
update public.books set slug = 'hooked' where slug is null and title = 'Hooked';
update public.books set slug = 'the-hard-thing-about-hard-things' where slug is null and title = 'The Hard Thing About Hard Things';
update public.books set slug = 'founders-at-work' where slug is null and title = 'Founders at Work';
update public.books set slug = 'blitzscaling' where slug is null and title = 'Blitzscaling';
update public.books set slug = 'venture-deals' where slug is null and title = 'Venture Deals';
update public.books set slug = 'obviously-awesome' where slug is null and title = 'Obviously Awesome';
update public.books set slug = 'getting-things-done' where slug is null and title = 'Getting Things Done';
update public.books set slug = 'make-time' where slug is null and title = 'Make Time';
update public.books set slug = 'the-one-thing' where slug is null and title = 'The ONE Thing';
update public.books set slug = 'four-thousand-weeks' where slug is null and title = 'Four Thousand Weeks';
update public.books set slug = 'eat-that-frog' where slug is null and title = 'Eat That Frog!';
update public.books set slug = 'the-checklist-manifesto' where slug is null and title = 'The Checklist Manifesto';
update public.books set slug = 'the-80-20-principle' where slug is null and title = 'The 80/20 Principle';
update public.books set slug = 'digital-minimalism' where slug is null and title = 'Digital Minimalism';
update public.books set slug = 'why-we-sleep' where slug is null and title = 'Why We Sleep';
update public.books set slug = 'breath' where slug is null and title = 'Breath';
update public.books set slug = 'the-body-keeps-the-score' where slug is null and title = 'The Body Keeps the Score';
update public.books set slug = 'how-not-to-die' where slug is null and title = 'How Not to Die';
update public.books set slug = 'spark' where slug is null and title = 'Spark';
update public.books set slug = 'in-defense-of-food' where slug is null and title = 'In Defense of Food';
update public.books set slug = 'the-comfort-crisis' where slug is null and title = 'The Comfort Crisis';
update public.books set slug = 'the-myth-of-sisyphus' where slug is null and title = 'The Myth of Sisyphus';
update public.books set slug = 'zen-mind-beginner-s-mind' where slug is null and title = 'Zen Mind, Beginner''s Mind';
update public.books set slug = 'steve-jobs' where slug is null and title = 'Steve Jobs';
update public.books set slug = 'shoe-dog' where slug is null and title = 'Shoe Dog';
update public.books set slug = 'the-ride-of-a-lifetime' where slug is null and title = 'The Ride of a Lifetime';
update public.books set slug = 'becoming' where slug is null and title = 'Becoming';
update public.books set slug = 'benjamin-franklin' where slug is null and title = 'Benjamin Franklin';
update public.books set slug = 'leonardo-da-vinci' where slug is null and title = 'Leonardo da Vinci';
update public.books set slug = 'team-of-rivals' where slug is null and title = 'Team of Rivals';
update public.books set slug = 'the-lessons-of-history' where slug is null and title = 'The Lessons of History';
update public.books set slug = 'the-silk-roads' where slug is null and title = 'The Silk Roads';
update public.books set slug = 'the-wright-brothers' where slug is null and title = 'The Wright Brothers';
update public.books set slug = 'attached' where slug is null and title = 'Attached';
update public.books set slug = 'hold-me-tight' where slug is null and title = 'Hold Me Tight';
update public.books set slug = 'the-seven-principles-for-making-marriage-work' where slug is null and title = 'The Seven Principles for Making Marriage Work';
update public.books set slug = 'dare-to-lead' where slug is null and title = 'Dare to Lead';
update public.books set slug = 'leaders-eat-last' where slug is null and title = 'Leaders Eat Last';
update public.books set slug = 'extreme-ownership' where slug is null and title = 'Extreme Ownership';
update public.books set slug = 'the-let-them-theory' where slug is null and title = 'The Let Them Theory';
update public.books set slug = 'the-anxious-generation' where slug is null and title = 'The Anxious Generation';
update public.books set slug = 'the-next-conversation' where slug is null and title = 'The Next Conversation';
update public.books set slug = 'everything-is-tuberculosis' where slug is null and title = 'Everything Is Tuberculosis';
update public.books set slug = 'the-coming-wave' where slug is null and title = 'The Coming Wave';
update public.books set slug = 'co-intelligence' where slug is null and title = 'Co-Intelligence';
update public.books set slug = 'nexus' where slug is null and title = 'Nexus';
update public.books set slug = 'the-alignment-problem' where slug is null and title = 'The Alignment Problem';
update public.books set slug = 'the-age-of-ai' where slug is null and title = 'The Age of AI';
update public.books set slug = 'life-3-0' where slug is null and title = 'Life 3.0';
update public.books set slug = 'superintelligence' where slug is null and title = 'Superintelligence';
update public.books set slug = 'algorithms-to-live-by' where slug is null and title = 'Algorithms to Live By';
update public.books set slug = 'weapons-of-math-destruction' where slug is null and title = 'Weapons of Math Destruction';
update public.books set slug = 'the-innovators' where slug is null and title = 'The Innovators';
update public.books set slug = 'chip-war' where slug is null and title = 'Chip War';
update public.books set slug = 'the-code-breaker' where slug is null and title = 'The Code Breaker';
update public.books set slug = 'the-worlds-i-see' where slug is null and title = 'The Worlds I See';
update public.books set slug = 'prediction-machines' where slug is null and title = 'Prediction Machines';
update public.books set slug = 'human-compatible' where slug is null and title = 'Human Compatible';
update public.books set slug = 'the-second-machine-age' where slug is null and title = 'The Second Machine Age';
update public.books set slug = 'the-shallows' where slug is null and title = 'The Shallows';
update public.books set slug = 'the-singularity-is-nearer' where slug is null and title = 'The Singularity Is Nearer';
update public.books set slug = 'ai-2041' where slug is null and title = 'AI 2041';
update public.books set slug = 'power-and-prediction' where slug is null and title = 'Power and Prediction';
update public.books set slug = 'a-brief-history-of-time' where slug is null and title = 'A Brief History of Time';
update public.books set slug = 'the-gene' where slug is null and title = 'The Gene';
update public.books set slug = 'the-emperor-of-all-maladies' where slug is null and title = 'The Emperor of All Maladies';
update public.books set slug = 'the-demon-haunted-world' where slug is null and title = 'The Demon-Haunted World';
update public.books set slug = 'cosmos' where slug is null and title = 'Cosmos';
update public.books set slug = 'the-immortal-life-of-henrietta-lacks' where slug is null and title = 'The Immortal Life of Henrietta Lacks';
update public.books set slug = 'entangled-life' where slug is null and title = 'Entangled Life';
update public.books set slug = 'an-immense-world' where slug is null and title = 'An Immense World';
update public.books set slug = 'the-sixth-extinction' where slug is null and title = 'The Sixth Extinction';
update public.books set slug = 'the-order-of-time' where slug is null and title = 'The Order of Time';
update public.books set slug = 'the-song-of-the-cell' where slug is null and title = 'The Song of the Cell';
update public.books set slug = 'astrophysics-for-people-in-a-hurry' where slug is null and title = 'Astrophysics for People in a Hurry';
update public.books set slug = 'immune' where slug is null and title = 'Immune';
update public.books set slug = 'why-we-get-sick' where slug is null and title = 'Why We Get Sick';
update public.books set slug = 'exercised' where slug is null and title = 'Exercised';
update public.books set slug = 'being-mortal' where slug is null and title = 'Being Mortal';
update public.books set slug = 'the-wealth-of-nations' where slug is null and title = 'The Wealth of Nations';
update public.books set slug = 'capital-in-the-twenty-first-century' where slug is null and title = 'Capital in the Twenty-First Century';
update public.books set slug = 'poor-economics' where slug is null and title = 'Poor Economics';
update public.books set slug = 'good-economics-for-hard-times' where slug is null and title = 'Good Economics for Hard Times';
update public.books set slug = 'the-undercover-economist' where slug is null and title = 'The Undercover Economist';
update public.books set slug = 'freakonomics' where slug is null and title = 'Freakonomics';
update public.books set slug = 'misbehaving' where slug is null and title = 'Misbehaving';
update public.books set slug = 'nudge' where slug is null and title = 'Nudge';
update public.books set slug = 'the-deficit-myth' where slug is null and title = 'The Deficit Myth';
update public.books set slug = 'doughnut-economics' where slug is null and title = 'Doughnut Economics';
update public.books set slug = 'why-nations-fail' where slug is null and title = 'Why Nations Fail';
update public.books set slug = 'the-ascent-of-money' where slug is null and title = 'The Ascent of Money';
update public.books set slug = 'the-great-transformation' where slug is null and title = 'The Great Transformation';
update public.books set slug = 'naked-economics' where slug is null and title = 'Naked Economics';
update public.books set slug = 'scarcity' where slug is null and title = 'Scarcity';
update public.books set slug = 'the-creative-act' where slug is null and title = 'The Creative Act';
update public.books set slug = 'big-magic' where slug is null and title = 'Big Magic';
update public.books set slug = 'steal-like-an-artist' where slug is null and title = 'Steal Like an Artist';
update public.books set slug = 'show-your-work' where slug is null and title = 'Show Your Work!';
update public.books set slug = 'keep-going' where slug is null and title = 'Keep Going';
update public.books set slug = 'the-artist-s-way' where slug is null and title = 'The Artist''s Way';
update public.books set slug = 'creativity-inc' where slug is null and title = 'Creativity, Inc.';
update public.books set slug = 'bird-by-bird' where slug is null and title = 'Bird by Bird';
update public.books set slug = 'on-writing' where slug is null and title = 'On Writing';
update public.books set slug = 'originals' where slug is null and title = 'Originals';
update public.books set slug = 'lateral-thinking' where slug is null and title = 'Lateral Thinking';
update public.books set slug = 'a-technique-for-producing-ideas' where slug is null and title = 'A Technique for Producing Ideas';
update public.books set slug = 'the-practice' where slug is null and title = 'The Practice';
update public.books set slug = 'creative-confidence' where slug is null and title = 'Creative Confidence';
update public.books set slug = 'the-accidental-creative' where slug is null and title = 'The Accidental Creative';
update public.books set slug = 'so-good-they-can-t-ignore-you' where slug is null and title = 'So Good They Can''t Ignore You';
update public.books set slug = 'designing-your-life' where slug is null and title = 'Designing Your Life';
update public.books set slug = 'range' where slug is null and title = 'Range';
update public.books set slug = 'give-and-take' where slug is null and title = 'Give and Take';
update public.books set slug = 'the-third-door' where slug is null and title = 'The Third Door';
update public.books set slug = 'the-startup-of-you' where slug is null and title = 'The Startup of You';
update public.books set slug = 'working-identity' where slug is null and title = 'Working Identity';
update public.books set slug = 'the-long-game' where slug is null and title = 'The Long Game';
update public.books set slug = 'the-good-enough-job' where slug is null and title = 'The Good Enough Job';
update public.books set slug = 'slow-productivity' where slug is null and title = 'Slow Productivity';
update public.books set slug = 'the-pathless-path' where slug is null and title = 'The Pathless Path';
update public.books set slug = 'the-defining-decade' where slug is null and title = 'The Defining Decade';
update public.books set slug = 'the-first-90-days' where slug is null and title = 'The First 90 Days';
update public.books set slug = 'bowling-alone' where slug is null and title = 'Bowling Alone';
update public.books set slug = 'the-coddling-of-the-american-mind' where slug is null and title = 'The Coddling of the American Mind';
update public.books set slug = 'amusing-ourselves-to-death' where slug is null and title = 'Amusing Ourselves to Death';
update public.books set slug = 'the-status-game' where slug is null and title = 'The Status Game';
update public.books set slug = 'the-dawn-of-everything' where slug is null and title = 'The Dawn of Everything';
update public.books set slug = 'the-weirdest-people-in-the-world' where slug is null and title = 'The WEIRDest People in the World';
update public.books set slug = 'evicted' where slug is null and title = 'Evicted';
update public.books set slug = 'caste' where slug is null and title = 'Caste';
update public.books set slug = 'invisible-women' where slug is null and title = 'Invisible Women';
update public.books set slug = 'on-tyranny' where slug is null and title = 'On Tyranny';
update public.books set slug = 'set-boundaries-find-peace' where slug is null and title = 'Set Boundaries, Find Peace';
update public.books set slug = 'all-about-love' where slug is null and title = 'All About Love';
update public.books set slug = 'mating-in-captivity' where slug is null and title = 'Mating in Captivity';
update public.books set slug = 'the-state-of-affairs' where slug is null and title = 'The State of Affairs';
update public.books set slug = 'us' where slug is null and title = 'Us';
update public.books set slug = 'platonic' where slug is null and title = 'Platonic';
update public.books set slug = 'eight-dates' where slug is null and title = 'Eight Dates';
update public.books set slug = 'the-relationship-cure' where slug is null and title = 'The Relationship Cure';
update public.books set slug = 'secure-love' where slug is null and title = 'Secure Love';
update public.books set slug = 'come-together' where slug is null and title = 'Come Together';
update public.books set slug = 'fight-right' where slug is null and title = 'Fight Right';
update public.books set slug = 'elon-musk' where slug is null and title = 'Elon Musk';
update public.books set slug = 'the-snowball' where slug is null and title = 'The Snowball';
update public.books set slug = 'titan' where slug is null and title = 'Titan';
update public.books set slug = 'alexander-hamilton' where slug is null and title = 'Alexander Hamilton';
update public.books set slug = 'educated' where slug is null and title = 'Educated';
update public.books set slug = 'born-a-crime' where slug is null and title = 'Born a Crime';
update public.books set slug = 'disciplined-entrepreneurship' where slug is null and title = 'Disciplined Entrepreneurship';
update public.books set slug = 'the-startup-owner-s-manual' where slug is null and title = 'The Startup Owner''s Manual';
update public.books set slug = 'the-cold-start-problem' where slug is null and title = 'The Cold Start Problem';
update public.books set slug = 'the-founder-s-dilemmas' where slug is null and title = 'The Founder''s Dilemmas';
update public.books set slug = 'the-little-book-that-still-beats-the-market' where slug is null and title = 'The Little Book That Still Beats the Market';
update public.books set slug = 'the-outsiders' where slug is null and title = 'The Outsiders';
update public.books set slug = 'the-black-swan' where slug is null and title = 'The Black Swan';
update public.books set slug = 'against-the-gods' where slug is null and title = 'Against the Gods';
update public.books set slug = 'the-big-short' where slug is null and title = 'The Big Short';
-- Any book that exists only in the database (the four public-domain classics)
-- gets the same transformation applied in SQL: lowercase, non-alphanumeric runs
-- collapsed to a hyphen, hyphens trimmed from both ends.
update public.books
set slug = trim(both '-' from regexp_replace(lower(title), '[^a-z0-9]+', '-', 'g'))
where slug is null;

alter table public.books alter column slug set not null;

create unique index if not exists books_slug_key on public.books(slug);
