begin;

insert into public.genres (name, slug)
values
  ('Business', 'business'),
  ('Finance', 'finance'),
  ('Investing', 'investing'),
  ('Personal Growth', 'personal-growth'),
  ('Communication', 'communication'),
  ('Psychology', 'psychology'),
  ('Startups', 'startups'),
  ('Productivity', 'productivity'),
  ('Health', 'health'),
  ('Philosophy', 'philosophy'),
  ('Biography', 'biography'),
  ('History', 'history'),
  ('Relationships', 'relationships'),
  ('Leadership', 'leadership'),
  ('Technology & AI', 'technology-ai'),
  ('Science', 'science'),
  ('Economics', 'economics'),
  ('Creativity', 'creativity'),
  ('Career', 'career'),
  ('Society & Culture', 'society-culture')
on conflict (slug) do update set name = excluded.name;

with catalog(title, author, published_year) as (
  values
  ('Atomic Habits', 'James Clear', 2018),
  ('The Psychology of Money', 'Morgan Housel', 2020),
  ('Deep Work', 'Cal Newport', 2016),
  ('Zero to One', 'Peter Thiel and Blake Masters', 2014),
  ('Thinking, Fast and Slow', 'Daniel Kahneman', 2011),
  ('Good to Great', 'Jim Collins', 2001),
  ('Meditations', 'Marcus Aurelius', 180),
  ('Sapiens', 'Yuval Noah Harari', 2011),
  ('Never Split the Difference', 'Chris Voss and Tahl Raz', 2016),
  ('Outlive', 'Peter Attia and Bill Gifford', 2023),
  ('The Innovator''s Dilemma', 'Clayton M. Christensen', 1997),
  ('High Output Management', 'Andrew S. Grove', 1983),
  ('The Effective Executive', 'Peter F. Drucker', 1966),
  ('Crossing the Chasm', 'Geoffrey A. Moore', 1991),
  ('Blue Ocean Strategy', 'W. Chan Kim and Renee Mauborgne', 2005),
  ('The Lean Startup', 'Eric Ries', 2011),
  ('Built to Last', 'Jim Collins and Jerry I. Porras', 1994),
  ('Measure What Matters', 'John Doerr', 2018),
  ('Rework', 'Jason Fried and David Heinemeier Hansson', 2010),
  ('The Intelligent Investor', 'Benjamin Graham', 1949),
  ('A Random Walk Down Wall Street', 'Burton G. Malkiel', 1973),
  ('The Millionaire Next Door', 'Thomas J. Stanley and William D. Danko', 1996),
  ('Your Money or Your Life', 'Vicki Robin and Joe Dominguez', 1992),
  ('The Richest Man in Babylon', 'George S. Clason', 1926),
  ('The Little Book of Common Sense Investing', 'John C. Bogle', 2007),
  ('Common Stocks and Uncommon Profits', 'Philip A. Fisher', 1958),
  ('Fooled by Randomness', 'Nassim Nicholas Taleb', 2001),
  ('The Simple Path to Wealth', 'J. L. Collins', 2016),
  ('One Up On Wall Street', 'Peter Lynch', 1989),
  ('Security Analysis', 'Benjamin Graham and David Dodd', 1934),
  ('The Most Important Thing', 'Howard Marks', 2011),
  ('The Essays of Warren Buffett', 'Warren E. Buffett; edited by Lawrence A. Cunningham', 1997),
  ('Reminiscences of a Stock Operator', 'Edwin Lefevre', 1923),
  ('Market Wizards', 'Jack D. Schwager', 1989),
  ('The Dhandho Investor', 'Mohnish Pabrai', 2007),
  ('The Warren Buffett Way', 'Robert G. Hagstrom', 1994),
  ('Mindset', 'Carol S. Dweck', 2006),
  ('The 7 Habits of Highly Effective People', 'Stephen R. Covey', 1989),
  ('Essentialism', 'Greg McKeown', 2014),
  ('The War of Art', 'Steven Pressfield', 2002),
  ('The Obstacle Is the Way', 'Ryan Holiday', 2014),
  ('Can''t Hurt Me', 'David Goggins', 2018),
  ('Make Your Bed', 'William H. McRaven', 2017),
  ('Man''s Search for Meaning', 'Viktor E. Frankl', 1946),
  ('How to Win Friends and Influence People', 'Dale Carnegie', 1936),
  ('Crucial Conversations', 'Kerry Patterson, Joseph Grenny, Ron McMillan, and Al Switzler', 2002),
  ('Nonviolent Communication', 'Marshall B. Rosenberg', 1999),
  ('Made to Stick', 'Chip Heath and Dan Heath', 2007),
  ('Influence', 'Robert B. Cialdini', 1984),
  ('Talk Like TED', 'Carmine Gallo', 2014),
  ('Difficult Conversations', 'Douglas Stone, Bruce Patton, and Sheila Heen', 1999),
  ('On Writing Well', 'William Zinsser', 1976),
  ('Everybody Writes', 'Ann Handley', 2014),
  ('Predictably Irrational', 'Dan Ariely', 2008),
  ('Flow', 'Mihaly Csikszentmihalyi', 1990),
  ('The Power of Habit', 'Charles Duhigg', 2012),
  ('Grit', 'Angela Duckworth', 2016),
  ('Stumbling on Happiness', 'Daniel Gilbert', 2006),
  ('The Righteous Mind', 'Jonathan Haidt', 2012),
  ('Quiet', 'Susan Cain', 2012),
  ('Drive', 'Daniel H. Pink', 2009),
  ('The Mom Test', 'Rob Fitzpatrick', 2013),
  ('Traction', 'Gabriel Weinberg and Justin Mares', 2014),
  ('Inspired', 'Marty Cagan', 2008),
  ('Hooked', 'Nir Eyal', 2014),
  ('The Hard Thing About Hard Things', 'Ben Horowitz', 2014),
  ('Founders at Work', 'Jessica Livingston', 2007),
  ('Blitzscaling', 'Reid Hoffman and Chris Yeh', 2018),
  ('Venture Deals', 'Brad Feld and Jason Mendelson', 2011),
  ('Obviously Awesome', 'April Dunford', 2019),
  ('Getting Things Done', 'David Allen', 2001),
  ('Make Time', 'Jake Knapp and John Zeratsky', 2018),
  ('The ONE Thing', 'Gary Keller and Jay Papasan', 2013),
  ('Four Thousand Weeks', 'Oliver Burkeman', 2021),
  ('Eat That Frog!', 'Brian Tracy', 2001),
  ('The Checklist Manifesto', 'Atul Gawande', 2009),
  ('The 80/20 Principle', 'Richard Koch', 1997),
  ('Digital Minimalism', 'Cal Newport', 2019),
  ('Why We Sleep', 'Matthew Walker', 2017),
  ('Breath', 'James Nestor', 2020),
  ('The Body Keeps the Score', 'Bessel van der Kolk', 2014),
  ('How Not to Die', 'Michael Greger', 2015),
  ('Spark', 'John J. Ratey', 2008),
  ('In Defense of Food', 'Michael Pollan', 2008),
  ('The Comfort Crisis', 'Michael Easter', 2021),
  ('Letters from a Stoic', 'Seneca', 65),
  ('The Republic', 'Plato', -375),
  ('Nicomachean Ethics', 'Aristotle', -340),
  ('Tao Te Ching', 'Laozi', -400),
  ('The Myth of Sisyphus', 'Albert Camus', 1942),
  ('Zen Mind, Beginner''s Mind', 'Shunryu Suzuki', 1970),
  ('Steve Jobs', 'Walter Isaacson', 2011),
  ('Shoe Dog', 'Phil Knight', 2016),
  ('The Ride of a Lifetime', 'Robert Iger', 2019),
  ('Becoming', 'Michelle Obama', 2018),
  ('Benjamin Franklin', 'Walter Isaacson', 2003),
  ('Leonardo da Vinci', 'Walter Isaacson', 2017),
  ('Team of Rivals', 'Doris Kearns Goodwin', 2005),
  ('The Lessons of History', 'Will and Ariel Durant', 1968),
  ('The Silk Roads', 'Peter Frankopan', 2015),
  ('The Wright Brothers', 'David McCullough', 2015),
  ('Attached', 'Amir Levine and Rachel Heller', 2010),
  ('Hold Me Tight', 'Sue Johnson', 2008),
  ('The Seven Principles for Making Marriage Work', 'John Gottman and Nan Silver', 1999),
  ('Dare to Lead', 'Brene Brown', 2018),
  ('Leaders Eat Last', 'Simon Sinek', 2014),
  ('Extreme Ownership', 'Jocko Willink and Leif Babin', 2015),
  ('The Let Them Theory', 'Mel Robbins', 2024),
  ('The Anxious Generation', 'Jonathan Haidt', 2024),
  ('The Next Conversation', 'Jefferson Fisher', 2025),
  ('Everything Is Tuberculosis', 'John Green', 2025),
  ('The Coming Wave', 'Mustafa Suleyman and Michael Bhaskar', 2023),
  ('Co-Intelligence', 'Ethan Mollick', 2024),
  ('Nexus', 'Yuval Noah Harari', 2024),
  ('The Alignment Problem', 'Brian Christian', 2020),
  ('The Age of AI', 'Henry Kissinger, Eric Schmidt, and Daniel Huttenlocher', 2021),
  ('Life 3.0', 'Max Tegmark', 2017),
  ('Superintelligence', 'Nick Bostrom', 2014),
  ('Algorithms to Live By', 'Brian Christian and Tom Griffiths', 2016),
  ('Weapons of Math Destruction', 'Cathy O''Neil', 2016),
  ('The Innovators', 'Walter Isaacson', 2014),
  ('Chip War', 'Chris Miller', 2022),
  ('The Code Breaker', 'Walter Isaacson', 2021),
  ('The Worlds I See', 'Fei-Fei Li', 2023),
  ('Prediction Machines', 'Ajay Agrawal, Joshua Gans, and Avi Goldfarb', 2018),
  ('Human Compatible', 'Stuart Russell', 2019),
  ('The Second Machine Age', 'Erik Brynjolfsson and Andrew McAfee', 2014),
  ('The Shallows', 'Nicholas Carr', 2010),
  ('The Singularity Is Nearer', 'Ray Kurzweil', 2024),
  ('AI 2041', 'Kai-Fu Lee and Chen Qiufan', 2021),
  ('Power and Prediction', 'Ajay Agrawal, Joshua Gans, and Avi Goldfarb', 2022),
  ('A Brief History of Time', 'Stephen Hawking', 1988),
  ('The Gene', 'Siddhartha Mukherjee', 2016),
  ('The Emperor of All Maladies', 'Siddhartha Mukherjee', 2010),
  ('The Demon-Haunted World', 'Carl Sagan', 1995),
  ('Cosmos', 'Carl Sagan', 1980),
  ('The Immortal Life of Henrietta Lacks', 'Rebecca Skloot', 2010),
  ('Entangled Life', 'Merlin Sheldrake', 2020),
  ('An Immense World', 'Ed Yong', 2022),
  ('The Sixth Extinction', 'Elizabeth Kolbert', 2014),
  ('The Order of Time', 'Carlo Rovelli', 2017),
  ('The Song of the Cell', 'Siddhartha Mukherjee', 2022),
  ('Astrophysics for People in a Hurry', 'Neil deGrasse Tyson', 2017),
  ('Immune', 'Philipp Dettmer', 2021),
  ('Why We Get Sick', 'Benjamin Bikman', 2020),
  ('Exercised', 'Daniel E. Lieberman', 2021),
  ('Being Mortal', 'Atul Gawande', 2014),
  ('The Wealth of Nations', 'Adam Smith', 1776),
  ('Capital in the Twenty-First Century', 'Thomas Piketty', 2013),
  ('Poor Economics', 'Abhijit V. Banerjee and Esther Duflo', 2011),
  ('Good Economics for Hard Times', 'Abhijit V. Banerjee and Esther Duflo', 2019),
  ('The Undercover Economist', 'Tim Harford', 2005),
  ('Freakonomics', 'Steven D. Levitt and Stephen J. Dubner', 2005),
  ('Misbehaving', 'Richard H. Thaler', 2015),
  ('Nudge', 'Richard H. Thaler and Cass R. Sunstein', 2008),
  ('The Deficit Myth', 'Stephanie Kelton', 2020),
  ('Doughnut Economics', 'Kate Raworth', 2017),
  ('Why Nations Fail', 'Daron Acemoglu and James A. Robinson', 2012),
  ('The Ascent of Money', 'Niall Ferguson', 2008),
  ('The Great Transformation', 'Karl Polanyi', 1944),
  ('Naked Economics', 'Charles Wheelan', 2002),
  ('Scarcity', 'Sendhil Mullainathan and Eldar Shafir', 2013),
  ('The Creative Act', 'Rick Rubin', 2023),
  ('Big Magic', 'Elizabeth Gilbert', 2015),
  ('Steal Like an Artist', 'Austin Kleon', 2012),
  ('Show Your Work!', 'Austin Kleon', 2014),
  ('Keep Going', 'Austin Kleon', 2019),
  ('The Artist''s Way', 'Julia Cameron', 1992),
  ('Creativity, Inc.', 'Ed Catmull and Amy Wallace', 2014),
  ('Bird by Bird', 'Anne Lamott', 1994),
  ('On Writing', 'Stephen King', 2000),
  ('Originals', 'Adam Grant', 2016),
  ('Lateral Thinking', 'Edward de Bono', 1970),
  ('A Technique for Producing Ideas', 'James Webb Young', 1940),
  ('The Practice', 'Seth Godin', 2020),
  ('Creative Confidence', 'Tom Kelley and David Kelley', 2013),
  ('The Accidental Creative', 'Todd Henry', 2011),
  ('So Good They Can''t Ignore You', 'Cal Newport', 2012),
  ('Designing Your Life', 'Bill Burnett and Dave Evans', 2016),
  ('Range', 'David Epstein', 2019),
  ('Give and Take', 'Adam Grant', 2013),
  ('The Third Door', 'Alex Banayan', 2018),
  ('The Startup of You', 'Reid Hoffman and Ben Casnocha', 2012),
  ('Working Identity', 'Herminia Ibarra', 2003),
  ('The Long Game', 'Dorie Clark', 2021),
  ('The Good Enough Job', 'Simone Stolzoff', 2023),
  ('Slow Productivity', 'Cal Newport', 2024),
  ('The Pathless Path', 'Paul Millerd', 2022),
  ('The Defining Decade', 'Meg Jay', 2012),
  ('The First 90 Days', 'Michael D. Watkins', 2003),
  ('Bowling Alone', 'Robert D. Putnam', 2000),
  ('The Coddling of the American Mind', 'Greg Lukianoff and Jonathan Haidt', 2018),
  ('Amusing Ourselves to Death', 'Neil Postman', 1985),
  ('The Status Game', 'Will Storr', 2021),
  ('The Dawn of Everything', 'David Graeber and David Wengrow', 2021),
  ('The WEIRDest People in the World', 'Joseph Henrich', 2020),
  ('Evicted', 'Matthew Desmond', 2016),
  ('Caste', 'Isabel Wilkerson', 2020),
  ('Invisible Women', 'Caroline Criado Perez', 2019),
  ('On Tyranny', 'Timothy Snyder', 2017),
  ('Set Boundaries, Find Peace', 'Nedra Glover Tawwab', 2021),
  ('All About Love', 'bell hooks', 2000),
  ('Mating in Captivity', 'Esther Perel', 2006),
  ('The State of Affairs', 'Esther Perel', 2017),
  ('Us', 'Terrence Real', 2022),
  ('Platonic', 'Marisa G. Franco', 2022),
  ('Eight Dates', 'John Gottman, Julie Schwartz Gottman, Doug Abrams, and Rachel Carlton Abrams', 2019),
  ('The Relationship Cure', 'John Gottman and Joan DeClaire', 2001),
  ('Secure Love', 'Julie Menanno', 2024),
  ('Come Together', 'Emily Nagoski', 2024),
  ('Fight Right', 'John Gottman and Julie Schwartz Gottman', 2024),
  ('Elon Musk', 'Walter Isaacson', 2023),
  ('The Snowball', 'Alice Schroeder', 2008),
  ('Titan', 'Ron Chernow', 1998),
  ('Alexander Hamilton', 'Ron Chernow', 2004),
  ('Educated', 'Tara Westover', 2018),
  ('Born a Crime', 'Trevor Noah', 2016),
  ('Disciplined Entrepreneurship', 'Bill Aulet', 2013),
  ('The Startup Owner''s Manual', 'Steve Blank and Bob Dorf', 2012),
  ('The Cold Start Problem', 'Andrew Chen', 2021),
  ('The Founder''s Dilemmas', 'Noam Wasserman', 2012),
  ('The Little Book That Still Beats the Market', 'Joel Greenblatt', 2005),
  ('The Outsiders', 'William N. Thorndike', 2012),
  ('The Black Swan', 'Nassim Nicholas Taleb', 2007),
  ('Against the Gods', 'Peter L. Bernstein', 1996),
  ('The Big Short', 'Michael Lewis', 2010)
)
insert into public.books (
  title,
  author,
  published_year,
  description,
  why_matters,
  why_it_matters,
  discussion_count,
  insight_count,
  readers_count
)
select
  catalog.title,
  catalog.author,
  catalog.published_year,
  catalog.title || ' by ' || catalog.author || ' is cataloged on BookSphere for reader perspectives and book-specific discussion.',
  'Use reader perspectives to understand what people took from this book and decide whether it deserves your full attention.',
  'Use reader perspectives to understand what people took from this book and decide whether it deserves your full attention.',
  0,
  0,
  0
from catalog
where not exists (
  select 1
  from public.books existing
  where lower(existing.title) = lower(catalog.title)
);

with mappings(title, genre_name) as (
  values
  ('Atomic Habits', 'Personal Growth'),
  ('Atomic Habits', 'Productivity'),
  ('The Psychology of Money', 'Finance'),
  ('The Psychology of Money', 'Investing'),
  ('Deep Work', 'Productivity'),
  ('Deep Work', 'Personal Growth'),
  ('Deep Work', 'Career'),
  ('Zero to One', 'Startups'),
  ('Zero to One', 'Business'),
  ('Thinking, Fast and Slow', 'Psychology'),
  ('Thinking, Fast and Slow', 'Business'),
  ('Good to Great', 'Business'),
  ('Good to Great', 'Leadership'),
  ('Good to Great', 'Career'),
  ('Meditations', 'Philosophy'),
  ('Meditations', 'Personal Growth'),
  ('Sapiens', 'History'),
  ('Sapiens', 'Philosophy'),
  ('Never Split the Difference', 'Communication'),
  ('Never Split the Difference', 'Business'),
  ('Outlive', 'Health'),
  ('Outlive', 'Personal Growth'),
  ('The Innovator''s Dilemma', 'Business'),
  ('The Innovator''s Dilemma', 'Startups'),
  ('High Output Management', 'Business'),
  ('High Output Management', 'Leadership'),
  ('High Output Management', 'Productivity'),
  ('The Effective Executive', 'Business'),
  ('The Effective Executive', 'Leadership'),
  ('The Effective Executive', 'Productivity'),
  ('Crossing the Chasm', 'Business'),
  ('Crossing the Chasm', 'Startups'),
  ('Blue Ocean Strategy', 'Business'),
  ('The Lean Startup', 'Business'),
  ('The Lean Startup', 'Startups'),
  ('Built to Last', 'Business'),
  ('Built to Last', 'Leadership'),
  ('Measure What Matters', 'Business'),
  ('Measure What Matters', 'Startups'),
  ('Measure What Matters', 'Productivity'),
  ('Rework', 'Business'),
  ('Rework', 'Startups'),
  ('The Intelligent Investor', 'Finance'),
  ('The Intelligent Investor', 'Investing'),
  ('A Random Walk Down Wall Street', 'Finance'),
  ('A Random Walk Down Wall Street', 'Investing'),
  ('The Millionaire Next Door', 'Finance'),
  ('The Millionaire Next Door', 'Personal Growth'),
  ('Your Money or Your Life', 'Finance'),
  ('Your Money or Your Life', 'Personal Growth'),
  ('The Richest Man in Babylon', 'Finance'),
  ('The Richest Man in Babylon', 'Personal Growth'),
  ('The Little Book of Common Sense Investing', 'Finance'),
  ('The Little Book of Common Sense Investing', 'Investing'),
  ('Common Stocks and Uncommon Profits', 'Finance'),
  ('Common Stocks and Uncommon Profits', 'Investing'),
  ('Fooled by Randomness', 'Finance'),
  ('Fooled by Randomness', 'Psychology'),
  ('Fooled by Randomness', 'Investing'),
  ('The Simple Path to Wealth', 'Finance'),
  ('The Simple Path to Wealth', 'Investing'),
  ('One Up On Wall Street', 'Investing'),
  ('One Up On Wall Street', 'Finance'),
  ('Security Analysis', 'Investing'),
  ('Security Analysis', 'Finance'),
  ('The Most Important Thing', 'Investing'),
  ('The Most Important Thing', 'Finance'),
  ('The Essays of Warren Buffett', 'Investing'),
  ('The Essays of Warren Buffett', 'Biography'),
  ('Reminiscences of a Stock Operator', 'Investing'),
  ('Reminiscences of a Stock Operator', 'Biography'),
  ('Market Wizards', 'Investing'),
  ('Market Wizards', 'Biography'),
  ('The Dhandho Investor', 'Investing'),
  ('The Dhandho Investor', 'Business'),
  ('The Warren Buffett Way', 'Investing'),
  ('The Warren Buffett Way', 'Biography'),
  ('Mindset', 'Personal Growth'),
  ('Mindset', 'Psychology'),
  ('The 7 Habits of Highly Effective People', 'Personal Growth'),
  ('The 7 Habits of Highly Effective People', 'Leadership'),
  ('The 7 Habits of Highly Effective People', 'Career'),
  ('Essentialism', 'Personal Growth'),
  ('Essentialism', 'Productivity'),
  ('Essentialism', 'Career'),
  ('The War of Art', 'Personal Growth'),
  ('The War of Art', 'Productivity'),
  ('The War of Art', 'Creativity'),
  ('The Obstacle Is the Way', 'Personal Growth'),
  ('The Obstacle Is the Way', 'Philosophy'),
  ('Can''t Hurt Me', 'Personal Growth'),
  ('Can''t Hurt Me', 'Health'),
  ('Can''t Hurt Me', 'Biography'),
  ('Make Your Bed', 'Personal Growth'),
  ('Make Your Bed', 'Leadership'),
  ('Man''s Search for Meaning', 'Personal Growth'),
  ('Man''s Search for Meaning', 'Philosophy'),
  ('Man''s Search for Meaning', 'Psychology'),
  ('How to Win Friends and Influence People', 'Communication'),
  ('How to Win Friends and Influence People', 'Relationships'),
  ('How to Win Friends and Influence People', 'Leadership'),
  ('Crucial Conversations', 'Communication'),
  ('Crucial Conversations', 'Leadership'),
  ('Crucial Conversations', 'Relationships'),
  ('Nonviolent Communication', 'Communication'),
  ('Nonviolent Communication', 'Relationships'),
  ('Made to Stick', 'Communication'),
  ('Made to Stick', 'Business'),
  ('Made to Stick', 'Creativity'),
  ('Influence', 'Communication'),
  ('Influence', 'Psychology'),
  ('Influence', 'Business'),
  ('Talk Like TED', 'Communication'),
  ('Talk Like TED', 'Business'),
  ('Difficult Conversations', 'Communication'),
  ('Difficult Conversations', 'Relationships'),
  ('On Writing Well', 'Communication'),
  ('On Writing Well', 'Productivity'),
  ('On Writing Well', 'Creativity'),
  ('Everybody Writes', 'Communication'),
  ('Everybody Writes', 'Business'),
  ('Everybody Writes', 'Creativity'),
  ('Predictably Irrational', 'Psychology'),
  ('Predictably Irrational', 'Business'),
  ('Flow', 'Psychology'),
  ('Flow', 'Productivity'),
  ('Flow', 'Creativity'),
  ('The Power of Habit', 'Psychology'),
  ('The Power of Habit', 'Productivity'),
  ('The Power of Habit', 'Personal Growth'),
  ('Grit', 'Psychology'),
  ('Grit', 'Personal Growth'),
  ('Stumbling on Happiness', 'Psychology'),
  ('The Righteous Mind', 'Psychology'),
  ('The Righteous Mind', 'Philosophy'),
  ('Quiet', 'Psychology'),
  ('Quiet', 'Communication'),
  ('Drive', 'Psychology'),
  ('Drive', 'Business'),
  ('Drive', 'Leadership'),
  ('The Mom Test', 'Startups'),
  ('The Mom Test', 'Communication'),
  ('Traction', 'Startups'),
  ('Traction', 'Business'),
  ('Inspired', 'Startups'),
  ('Inspired', 'Business'),
  ('Hooked', 'Startups'),
  ('Hooked', 'Psychology'),
  ('The Hard Thing About Hard Things', 'Startups'),
  ('The Hard Thing About Hard Things', 'Leadership'),
  ('Founders at Work', 'Startups'),
  ('Founders at Work', 'Biography'),
  ('Blitzscaling', 'Startups'),
  ('Blitzscaling', 'Business'),
  ('Venture Deals', 'Startups'),
  ('Venture Deals', 'Finance'),
  ('Obviously Awesome', 'Startups'),
  ('Obviously Awesome', 'Communication'),
  ('Getting Things Done', 'Productivity'),
  ('Make Time', 'Productivity'),
  ('Make Time', 'Health'),
  ('Make Time', 'Career'),
  ('The ONE Thing', 'Productivity'),
  ('The ONE Thing', 'Business'),
  ('Four Thousand Weeks', 'Productivity'),
  ('Four Thousand Weeks', 'Philosophy'),
  ('Eat That Frog!', 'Productivity'),
  ('Eat That Frog!', 'Personal Growth'),
  ('The Checklist Manifesto', 'Productivity'),
  ('The Checklist Manifesto', 'Health'),
  ('The 80/20 Principle', 'Productivity'),
  ('The 80/20 Principle', 'Business'),
  ('Digital Minimalism', 'Productivity'),
  ('Digital Minimalism', 'Philosophy'),
  ('Why We Sleep', 'Health'),
  ('Why We Sleep', 'Productivity'),
  ('Breath', 'Health'),
  ('The Body Keeps the Score', 'Health'),
  ('The Body Keeps the Score', 'Psychology'),
  ('How Not to Die', 'Health'),
  ('Spark', 'Health'),
  ('Spark', 'Psychology'),
  ('In Defense of Food', 'Health'),
  ('The Comfort Crisis', 'Health'),
  ('The Comfort Crisis', 'Personal Growth'),
  ('Letters from a Stoic', 'Philosophy'),
  ('Letters from a Stoic', 'Personal Growth'),
  ('The Republic', 'Philosophy'),
  ('The Republic', 'History'),
  ('Nicomachean Ethics', 'Philosophy'),
  ('Tao Te Ching', 'Philosophy'),
  ('The Myth of Sisyphus', 'Philosophy'),
  ('Zen Mind, Beginner''s Mind', 'Philosophy'),
  ('Zen Mind, Beginner''s Mind', 'Personal Growth'),
  ('Steve Jobs', 'Biography'),
  ('Steve Jobs', 'Business'),
  ('Steve Jobs', 'Startups'),
  ('Shoe Dog', 'Biography'),
  ('Shoe Dog', 'Business'),
  ('The Ride of a Lifetime', 'Biography'),
  ('The Ride of a Lifetime', 'Leadership'),
  ('The Ride of a Lifetime', 'Business'),
  ('Becoming', 'Biography'),
  ('Becoming', 'Leadership'),
  ('Benjamin Franklin', 'Biography'),
  ('Benjamin Franklin', 'History'),
  ('Leonardo da Vinci', 'Biography'),
  ('Leonardo da Vinci', 'History'),
  ('Team of Rivals', 'History'),
  ('Team of Rivals', 'Leadership'),
  ('Team of Rivals', 'Biography'),
  ('The Lessons of History', 'History'),
  ('The Lessons of History', 'Philosophy'),
  ('The Silk Roads', 'History'),
  ('The Wright Brothers', 'History'),
  ('The Wright Brothers', 'Biography'),
  ('Attached', 'Relationships'),
  ('Attached', 'Psychology'),
  ('Hold Me Tight', 'Relationships'),
  ('Hold Me Tight', 'Psychology'),
  ('The Seven Principles for Making Marriage Work', 'Relationships'),
  ('The Seven Principles for Making Marriage Work', 'Psychology'),
  ('Dare to Lead', 'Leadership'),
  ('Dare to Lead', 'Communication'),
  ('Leaders Eat Last', 'Leadership'),
  ('Leaders Eat Last', 'Business'),
  ('Extreme Ownership', 'Leadership'),
  ('Extreme Ownership', 'Business'),
  ('The Let Them Theory', 'Personal Growth'),
  ('The Let Them Theory', 'Psychology'),
  ('The Let Them Theory', 'Relationships'),
  ('The Anxious Generation', 'Psychology'),
  ('The Anxious Generation', 'Society & Culture'),
  ('The Anxious Generation', 'Health'),
  ('The Next Conversation', 'Communication'),
  ('The Next Conversation', 'Relationships'),
  ('Everything Is Tuberculosis', 'Science'),
  ('Everything Is Tuberculosis', 'Health'),
  ('Everything Is Tuberculosis', 'History'),
  ('Everything Is Tuberculosis', 'Society & Culture'),
  ('The Coming Wave', 'Technology & AI'),
  ('The Coming Wave', 'Society & Culture'),
  ('The Coming Wave', 'Business'),
  ('Co-Intelligence', 'Technology & AI'),
  ('Co-Intelligence', 'Career'),
  ('Co-Intelligence', 'Business'),
  ('Co-Intelligence', 'Leadership'),
  ('Nexus', 'Technology & AI'),
  ('Nexus', 'History'),
  ('Nexus', 'Society & Culture'),
  ('The Alignment Problem', 'Technology & AI'),
  ('The Alignment Problem', 'Science'),
  ('The Alignment Problem', 'Society & Culture'),
  ('The Age of AI', 'Technology & AI'),
  ('The Age of AI', 'Society & Culture'),
  ('The Age of AI', 'Philosophy'),
  ('Life 3.0', 'Technology & AI'),
  ('Life 3.0', 'Science'),
  ('Life 3.0', 'Philosophy'),
  ('Superintelligence', 'Technology & AI'),
  ('Superintelligence', 'Science'),
  ('Superintelligence', 'Philosophy'),
  ('Algorithms to Live By', 'Technology & AI'),
  ('Algorithms to Live By', 'Science'),
  ('Algorithms to Live By', 'Psychology'),
  ('Weapons of Math Destruction', 'Technology & AI'),
  ('Weapons of Math Destruction', 'Society & Culture'),
  ('Weapons of Math Destruction', 'Economics'),
  ('The Innovators', 'Technology & AI'),
  ('The Innovators', 'Biography'),
  ('The Innovators', 'History'),
  ('Chip War', 'Technology & AI'),
  ('Chip War', 'History'),
  ('Chip War', 'Economics'),
  ('The Code Breaker', 'Science'),
  ('The Code Breaker', 'Technology & AI'),
  ('The Code Breaker', 'Biography'),
  ('The Worlds I See', 'Technology & AI'),
  ('The Worlds I See', 'Biography'),
  ('The Worlds I See', 'Science'),
  ('Prediction Machines', 'Technology & AI'),
  ('Prediction Machines', 'Economics'),
  ('Prediction Machines', 'Business'),
  ('Human Compatible', 'Technology & AI'),
  ('Human Compatible', 'Science'),
  ('Human Compatible', 'Philosophy'),
  ('The Second Machine Age', 'Technology & AI'),
  ('The Second Machine Age', 'Economics'),
  ('The Second Machine Age', 'Career'),
  ('The Shallows', 'Technology & AI'),
  ('The Shallows', 'Psychology'),
  ('The Shallows', 'Society & Culture'),
  ('The Singularity Is Nearer', 'Technology & AI'),
  ('The Singularity Is Nearer', 'Science'),
  ('AI 2041', 'Technology & AI'),
  ('AI 2041', 'Science'),
  ('AI 2041', 'Society & Culture'),
  ('Power and Prediction', 'Technology & AI'),
  ('Power and Prediction', 'Economics'),
  ('Power and Prediction', 'Business'),
  ('A Brief History of Time', 'Science'),
  ('A Brief History of Time', 'Philosophy'),
  ('The Gene', 'Science'),
  ('The Gene', 'Health'),
  ('The Gene', 'History'),
  ('The Emperor of All Maladies', 'Science'),
  ('The Emperor of All Maladies', 'Health'),
  ('The Emperor of All Maladies', 'History'),
  ('The Demon-Haunted World', 'Science'),
  ('The Demon-Haunted World', 'Philosophy'),
  ('Cosmos', 'Science'),
  ('Cosmos', 'History'),
  ('Cosmos', 'Philosophy'),
  ('The Immortal Life of Henrietta Lacks', 'Science'),
  ('The Immortal Life of Henrietta Lacks', 'Health'),
  ('The Immortal Life of Henrietta Lacks', 'Biography'),
  ('The Immortal Life of Henrietta Lacks', 'Society & Culture'),
  ('Entangled Life', 'Science'),
  ('An Immense World', 'Science'),
  ('The Sixth Extinction', 'Science'),
  ('The Sixth Extinction', 'History'),
  ('The Sixth Extinction', 'Society & Culture'),
  ('The Order of Time', 'Science'),
  ('The Order of Time', 'Philosophy'),
  ('The Song of the Cell', 'Science'),
  ('The Song of the Cell', 'Health'),
  ('Astrophysics for People in a Hurry', 'Science'),
  ('Immune', 'Science'),
  ('Immune', 'Health'),
  ('Why We Get Sick', 'Health'),
  ('Why We Get Sick', 'Science'),
  ('Exercised', 'Health'),
  ('Exercised', 'Science'),
  ('Being Mortal', 'Health'),
  ('Being Mortal', 'Society & Culture'),
  ('The Wealth of Nations', 'Economics'),
  ('The Wealth of Nations', 'History'),
  ('The Wealth of Nations', 'Philosophy'),
  ('Capital in the Twenty-First Century', 'Economics'),
  ('Capital in the Twenty-First Century', 'Finance'),
  ('Capital in the Twenty-First Century', 'History'),
  ('Poor Economics', 'Economics'),
  ('Poor Economics', 'Society & Culture'),
  ('Good Economics for Hard Times', 'Economics'),
  ('Good Economics for Hard Times', 'Society & Culture'),
  ('The Undercover Economist', 'Economics'),
  ('The Undercover Economist', 'Finance'),
  ('Freakonomics', 'Economics'),
  ('Freakonomics', 'Psychology'),
  ('Misbehaving', 'Economics'),
  ('Misbehaving', 'Psychology'),
  ('Misbehaving', 'Investing'),
  ('Nudge', 'Economics'),
  ('Nudge', 'Psychology'),
  ('Nudge', 'Society & Culture'),
  ('The Deficit Myth', 'Economics'),
  ('The Deficit Myth', 'Finance'),
  ('Doughnut Economics', 'Economics'),
  ('Doughnut Economics', 'Society & Culture'),
  ('Why Nations Fail', 'Economics'),
  ('Why Nations Fail', 'History'),
  ('Why Nations Fail', 'Society & Culture'),
  ('The Ascent of Money', 'Economics'),
  ('The Ascent of Money', 'Finance'),
  ('The Ascent of Money', 'Investing'),
  ('The Ascent of Money', 'History'),
  ('The Great Transformation', 'Economics'),
  ('The Great Transformation', 'History'),
  ('The Great Transformation', 'Society & Culture'),
  ('Naked Economics', 'Economics'),
  ('Naked Economics', 'Finance'),
  ('Scarcity', 'Economics'),
  ('Scarcity', 'Psychology'),
  ('Scarcity', 'Society & Culture'),
  ('The Creative Act', 'Creativity'),
  ('The Creative Act', 'Philosophy'),
  ('Big Magic', 'Creativity'),
  ('Big Magic', 'Personal Growth'),
  ('Steal Like an Artist', 'Creativity'),
  ('Steal Like an Artist', 'Career'),
  ('Show Your Work!', 'Creativity'),
  ('Show Your Work!', 'Career'),
  ('Show Your Work!', 'Communication'),
  ('Keep Going', 'Creativity'),
  ('Keep Going', 'Career'),
  ('Keep Going', 'Personal Growth'),
  ('The Artist''s Way', 'Creativity'),
  ('The Artist''s Way', 'Personal Growth'),
  ('Creativity, Inc.', 'Creativity'),
  ('Creativity, Inc.', 'Business'),
  ('Creativity, Inc.', 'Leadership'),
  ('Bird by Bird', 'Creativity'),
  ('Bird by Bird', 'Communication'),
  ('On Writing', 'Creativity'),
  ('On Writing', 'Communication'),
  ('On Writing', 'Biography'),
  ('Originals', 'Creativity'),
  ('Originals', 'Psychology'),
  ('Originals', 'Business'),
  ('Lateral Thinking', 'Creativity'),
  ('Lateral Thinking', 'Psychology'),
  ('A Technique for Producing Ideas', 'Creativity'),
  ('A Technique for Producing Ideas', 'Communication'),
  ('The Practice', 'Creativity'),
  ('The Practice', 'Career'),
  ('Creative Confidence', 'Creativity'),
  ('Creative Confidence', 'Business'),
  ('Creative Confidence', 'Career'),
  ('The Accidental Creative', 'Creativity'),
  ('The Accidental Creative', 'Productivity'),
  ('The Accidental Creative', 'Career'),
  ('So Good They Can''t Ignore You', 'Career'),
  ('So Good They Can''t Ignore You', 'Personal Growth'),
  ('Designing Your Life', 'Career'),
  ('Designing Your Life', 'Personal Growth'),
  ('Range', 'Career'),
  ('Range', 'Psychology'),
  ('Give and Take', 'Career'),
  ('Give and Take', 'Psychology'),
  ('Give and Take', 'Relationships'),
  ('Give and Take', 'Leadership'),
  ('The Third Door', 'Career'),
  ('The Third Door', 'Biography'),
  ('The Startup of You', 'Career'),
  ('The Startup of You', 'Business'),
  ('The Startup of You', 'Startups'),
  ('Working Identity', 'Career'),
  ('Working Identity', 'Psychology'),
  ('The Long Game', 'Career'),
  ('The Long Game', 'Business'),
  ('The Good Enough Job', 'Career'),
  ('The Good Enough Job', 'Society & Culture'),
  ('Slow Productivity', 'Career'),
  ('Slow Productivity', 'Productivity'),
  ('The Pathless Path', 'Career'),
  ('The Pathless Path', 'Personal Growth'),
  ('The Defining Decade', 'Career'),
  ('The Defining Decade', 'Psychology'),
  ('The Defining Decade', 'Relationships'),
  ('The First 90 Days', 'Career'),
  ('The First 90 Days', 'Leadership'),
  ('The First 90 Days', 'Business'),
  ('Bowling Alone', 'Society & Culture'),
  ('Bowling Alone', 'History'),
  ('Bowling Alone', 'Relationships'),
  ('The Coddling of the American Mind', 'Society & Culture'),
  ('The Coddling of the American Mind', 'Psychology'),
  ('Amusing Ourselves to Death', 'Society & Culture'),
  ('Amusing Ourselves to Death', 'Technology & AI'),
  ('Amusing Ourselves to Death', 'Philosophy'),
  ('The Status Game', 'Society & Culture'),
  ('The Status Game', 'Psychology'),
  ('The Dawn of Everything', 'Society & Culture'),
  ('The Dawn of Everything', 'History'),
  ('The WEIRDest People in the World', 'Society & Culture'),
  ('The WEIRDest People in the World', 'Psychology'),
  ('The WEIRDest People in the World', 'History'),
  ('Evicted', 'Society & Culture'),
  ('Evicted', 'Economics'),
  ('Caste', 'Society & Culture'),
  ('Caste', 'History'),
  ('Invisible Women', 'Society & Culture'),
  ('Invisible Women', 'Economics'),
  ('On Tyranny', 'Society & Culture'),
  ('On Tyranny', 'History'),
  ('On Tyranny', 'Philosophy'),
  ('Set Boundaries, Find Peace', 'Relationships'),
  ('Set Boundaries, Find Peace', 'Psychology'),
  ('Set Boundaries, Find Peace', 'Personal Growth'),
  ('All About Love', 'Relationships'),
  ('All About Love', 'Philosophy'),
  ('All About Love', 'Society & Culture'),
  ('Mating in Captivity', 'Relationships'),
  ('Mating in Captivity', 'Psychology'),
  ('The State of Affairs', 'Relationships'),
  ('The State of Affairs', 'Psychology'),
  ('Us', 'Relationships'),
  ('Us', 'Psychology'),
  ('Platonic', 'Relationships'),
  ('Platonic', 'Psychology'),
  ('Platonic', 'Society & Culture'),
  ('Eight Dates', 'Relationships'),
  ('Eight Dates', 'Communication'),
  ('The Relationship Cure', 'Relationships'),
  ('The Relationship Cure', 'Communication'),
  ('Secure Love', 'Relationships'),
  ('Secure Love', 'Psychology'),
  ('Come Together', 'Relationships'),
  ('Come Together', 'Health'),
  ('Fight Right', 'Relationships'),
  ('Fight Right', 'Communication'),
  ('Elon Musk', 'Biography'),
  ('Elon Musk', 'Business'),
  ('Elon Musk', 'Technology & AI'),
  ('The Snowball', 'Biography'),
  ('The Snowball', 'Investing'),
  ('The Snowball', 'Business'),
  ('Titan', 'Biography'),
  ('Titan', 'Business'),
  ('Titan', 'History'),
  ('Alexander Hamilton', 'Biography'),
  ('Alexander Hamilton', 'History'),
  ('Alexander Hamilton', 'Leadership'),
  ('Educated', 'Biography'),
  ('Educated', 'Society & Culture'),
  ('Born a Crime', 'Biography'),
  ('Born a Crime', 'Society & Culture'),
  ('Disciplined Entrepreneurship', 'Startups'),
  ('Disciplined Entrepreneurship', 'Business'),
  ('The Startup Owner''s Manual', 'Startups'),
  ('The Startup Owner''s Manual', 'Business'),
  ('The Cold Start Problem', 'Startups'),
  ('The Cold Start Problem', 'Business'),
  ('The Cold Start Problem', 'Technology & AI'),
  ('The Founder''s Dilemmas', 'Startups'),
  ('The Founder''s Dilemmas', 'Business'),
  ('The Founder''s Dilemmas', 'Leadership'),
  ('The Little Book That Still Beats the Market', 'Investing'),
  ('The Little Book That Still Beats the Market', 'Finance'),
  ('The Outsiders', 'Investing'),
  ('The Outsiders', 'Business'),
  ('The Outsiders', 'Leadership'),
  ('The Black Swan', 'Investing'),
  ('The Black Swan', 'Finance'),
  ('The Black Swan', 'Psychology'),
  ('Against the Gods', 'Investing'),
  ('Against the Gods', 'Finance'),
  ('Against the Gods', 'History'),
  ('The Big Short', 'Investing'),
  ('The Big Short', 'Finance'),
  ('The Big Short', 'History')
)
insert into public.book_genres (book_id, genre_id)
select books.id, genres.id
from mappings
join public.books books on lower(books.title) = lower(mappings.title)
join public.genres genres on genres.name = mappings.genre_name
on conflict do nothing;

commit;
