-- The catalog in src/lib/data.ts grew from 226 to 391 books, but community data lives
-- in this table: a book with no row here cannot host a discussion, a save, or a
-- recommendation. Without this sync, 168 of the books a visitor can browse would
-- silently refuse every community action - the same failure that stranded five books
-- before the slug key was introduced.
--
-- Inserted with the slug already set so the catalog joins on it immediately. Titles,
-- authors and years are generated from the catalog itself. Descriptions are a neutral
-- placeholder; the app renders its own editorial copy and only falls back to this.
--
-- Safe to re-run: the unique index on slug makes the conflict clause a no-op for books
-- already present.

insert into public.books (title, author, published_year, slug, description) values
  ('Homo Deus', 'Yuval Noah Harari', 2015, 'homo-deus', 'Homo Deus by Yuval Noah Harari.'),
  ('21 Lessons for the 21st Century', 'Yuval Noah Harari', 2018, '21-lessons-for-the-21st-century', '21 Lessons for the 21st Century by Yuval Noah Harari.'),
  ('Guns, Germs, and Steel', 'Jared Diamond', 1997, 'guns-germs-and-steel', 'Guns, Germs, and Steel by Jared Diamond.'),
  ('SPQR', 'Mary Beard', 2015, 'spqr', 'SPQR by Mary Beard.'),
  ('The Guns of August', 'Barbara W. Tuchman', 1962, 'the-guns-of-august', 'The Guns of August by Barbara W. Tuchman.'),
  ('A People''s History of the United States', 'Howard Zinn', 1980, 'a-people-s-history-of-the-united-states', 'A People''s History of the United States by Howard Zinn.'),
  ('The Rise and Fall of the Third Reich', 'William L. Shirer', 1960, 'the-rise-and-fall-of-the-third-reich', 'The Rise and Fall of the Third Reich by William L. Shirer.'),
  ('1776', 'David McCullough', 2005, '1776', '1776 by David McCullough.'),
  ('Salt', 'Mark Kurlansky', 2002, 'salt', 'Salt by Mark Kurlansky.'),
  ('The Devil in the White City', 'Erik Larson', 2003, 'the-devil-in-the-white-city', 'The Devil in the White City by Erik Larson.'),
  ('The Selfish Gene', 'Richard Dawkins', 1976, 'the-selfish-gene', 'The Selfish Gene by Richard Dawkins.'),
  ('Silent Spring', 'Rachel Carson', 1962, 'silent-spring', 'Silent Spring by Rachel Carson.'),
  ('The Body', 'Bill Bryson', 2019, 'the-body', 'The Body by Bill Bryson.'),
  ('A Short History of Nearly Everything', 'Bill Bryson', 2003, 'a-short-history-of-nearly-everything', 'A Short History of Nearly Everything by Bill Bryson.'),
  ('Behave', 'Robert M. Sapolsky', 2017, 'behave', 'Behave by Robert M. Sapolsky.'),
  ('Determined', 'Robert M. Sapolsky', 2023, 'determined', 'Determined by Robert M. Sapolsky.'),
  ('Why Zebras Don''t Get Ulcers', 'Robert M. Sapolsky', 1994, 'why-zebras-don-t-get-ulcers', 'Why Zebras Don''t Get Ulcers by Robert M. Sapolsky.'),
  ('Emotional Intelligence', 'Daniel Goleman', 1995, 'emotional-intelligence', 'Emotional Intelligence by Daniel Goleman.'),
  ('The Happiness Hypothesis', 'Jonathan Haidt', 2006, 'the-happiness-hypothesis', 'The Happiness Hypothesis by Jonathan Haidt.'),
  ('The Paradox of Choice', 'Barry Schwartz', 2004, 'the-paradox-of-choice', 'The Paradox of Choice by Barry Schwartz.'),
  ('Blink', 'Malcolm Gladwell', 2005, 'blink', 'Blink by Malcolm Gladwell.'),
  ('Outliers', 'Malcolm Gladwell', 2008, 'outliers', 'Outliers by Malcolm Gladwell.'),
  ('The Tipping Point', 'Malcolm Gladwell', 2000, 'the-tipping-point', 'The Tipping Point by Malcolm Gladwell.'),
  ('Talking to Strangers', 'Malcolm Gladwell', 2019, 'talking-to-strangers', 'Talking to Strangers by Malcolm Gladwell.'),
  ('David and Goliath', 'Malcolm Gladwell', 2013, 'david-and-goliath', 'David and Goliath by Malcolm Gladwell.'),
  ('Think Again', 'Adam Grant', 2021, 'think-again', 'Think Again by Adam Grant.'),
  ('Hidden Potential', 'Adam Grant', 2023, 'hidden-potential', 'Hidden Potential by Adam Grant.'),
  ('Chatter', 'Ethan Kross', 2021, 'chatter', 'Chatter by Ethan Kross.'),
  ('Stolen Focus', 'Johann Hari', 2022, 'stolen-focus', 'Stolen Focus by Johann Hari.'),
  ('Lifespan', 'David A. Sinclair', 2019, 'lifespan', 'Lifespan by David A. Sinclair.'),
  ('The Obesity Code', 'Jason Fung', 2016, 'the-obesity-code', 'The Obesity Code by Jason Fung.'),
  ('Burnout', 'Emily Nagoski', 2019, 'burnout', 'Burnout by Emily Nagoski.'),
  ('Good Energy', 'Casey Means', 2024, 'good-energy', 'Good Energy by Casey Means.'),
  ('Come As You Are', 'Emily Nagoski', 2015, 'come-as-you-are', 'Come As You Are by Emily Nagoski.'),
  ('On the Shortness of Life', 'Seneca', 49, 'on-the-shortness-of-life', 'On the Shortness of Life by Seneca.'),
  ('The Daily Stoic', 'Ryan Holiday', 2016, 'the-daily-stoic', 'The Daily Stoic by Ryan Holiday.'),
  ('Ego Is the Enemy', 'Ryan Holiday', 2016, 'ego-is-the-enemy', 'Ego Is the Enemy by Ryan Holiday.'),
  ('Stillness Is the Key', 'Ryan Holiday', 2019, 'stillness-is-the-key', 'Stillness Is the Key by Ryan Holiday.'),
  ('The Consolations of Philosophy', 'Alain de Botton', 2000, 'the-consolations-of-philosophy', 'The Consolations of Philosophy by Alain de Botton.'),
  ('Justice', 'Michael J. Sandel', 2009, 'justice', 'Justice by Michael J. Sandel.'),
  ('The Courage to Be Disliked', 'Ichiro Kishimi', 2013, 'the-courage-to-be-disliked', 'The Courage to Be Disliked by Ichiro Kishimi.'),
  ('The Age of Surveillance Capitalism', 'Shoshana Zuboff', 2019, 'the-age-of-surveillance-capitalism', 'The Age of Surveillance Capitalism by Shoshana Zuboff.'),
  ('Thinking in Systems', 'Donella H. Meadows', 2008, 'thinking-in-systems', 'Thinking in Systems by Donella H. Meadows.'),
  ('Basic Economics', 'Thomas Sowell', 2000, 'basic-economics', 'Basic Economics by Thomas Sowell.'),
  ('How the World Really Works', 'Vaclav Smil', 2022, 'how-the-world-really-works', 'How the World Really Works by Vaclav Smil.'),
  ('Good Strategy Bad Strategy', 'Richard P. Rumelt', 2011, 'good-strategy-bad-strategy', 'Good Strategy Bad Strategy by Richard P. Rumelt.'),
  ('The Personal MBA', 'Josh Kaufman', 2010, 'the-personal-mba', 'The Personal MBA by Josh Kaufman.'),
  ('Start with Why', 'Simon Sinek', 2009, 'start-with-why', 'Start with Why by Simon Sinek.'),
  ('The Infinite Game', 'Simon Sinek', 2019, 'the-infinite-game', 'The Infinite Game by Simon Sinek.'),
  ('Radical Candor', 'Kim Scott', 2017, 'radical-candor', 'Radical Candor by Kim Scott.'),
  ('The Five Dysfunctions of a Team', 'Patrick Lencioni', 2002, 'the-five-dysfunctions-of-a-team', 'The Five Dysfunctions of a Team by Patrick Lencioni.'),
  ('Multipliers', 'Liz Wiseman', 2010, 'multipliers', 'Multipliers by Liz Wiseman.'),
  ('Turn the Ship Around!', 'L. David Marquet', 2012, 'turn-the-ship-around', 'Turn the Ship Around! by L. David Marquet.'),
  ('No Rules Rules', 'Reed Hastings', 2020, 'no-rules-rules', 'No Rules Rules by Reed Hastings.'),
  ('The Culture Map', 'Erin Meyer', 2014, 'the-culture-map', 'The Culture Map by Erin Meyer.'),
  ('Working Backwards', 'Colin Bryar', 2021, 'working-backwards', 'Working Backwards by Colin Bryar.'),
  ('Build', 'Tony Fadell', 2022, 'build', 'Build by Tony Fadell.'),
  ('Company of One', 'Paul Jarvis', 2019, 'company-of-one', 'Company of One by Paul Jarvis.'),
  ('The E-Myth Revisited', 'Michael E. Gerber', 1995, 'the-e-myth-revisited', 'The E-Myth Revisited by Michael E. Gerber.'),
  ('Principles', 'Ray Dalio', 2017, 'principles', 'Principles by Ray Dalio.'),
  ('The Almanack of Naval Ravikant', 'Eric Jorgenson', 2020, 'the-almanack-of-naval-ravikant', 'The Almanack of Naval Ravikant by Eric Jorgenson.'),
  ('Delivering Happiness', 'Tony Hsieh', 2010, 'delivering-happiness', 'Delivering Happiness by Tony Hsieh.'),
  ('Setting the Table', 'Danny Meyer', 2006, 'setting-the-table', 'Setting the Table by Danny Meyer.'),
  ('Let My People Go Surfing', 'Yvon Chouinard', 2005, 'let-my-people-go-surfing', 'Let My People Go Surfing by Yvon Chouinard.'),
  ('Rich Dad Poor Dad', 'Robert T. Kiyosaki', 1997, 'rich-dad-poor-dad', 'Rich Dad Poor Dad by Robert T. Kiyosaki.'),
  ('I Will Teach You to Be Rich', 'Ramit Sethi', 2009, 'i-will-teach-you-to-be-rich', 'I Will Teach You to Be Rich by Ramit Sethi.'),
  ('The Total Money Makeover', 'Dave Ramsey', 2003, 'the-total-money-makeover', 'The Total Money Makeover by Dave Ramsey.'),
  ('Die with Zero', 'Bill Perkins', 2020, 'die-with-zero', 'Die with Zero by Bill Perkins.'),
  ('Just Keep Buying', 'Nick Maggiulli', 2022, 'just-keep-buying', 'Just Keep Buying by Nick Maggiulli.'),
  ('Same as Ever', 'Morgan Housel', 2023, 'same-as-ever', 'Same as Ever by Morgan Housel.'),
  ('The Algebra of Wealth', 'Scott Galloway', 2024, 'the-algebra-of-wealth', 'The Algebra of Wealth by Scott Galloway.'),
  ('A Man for All Markets', 'Edward O. Thorp', 2017, 'a-man-for-all-markets', 'A Man for All Markets by Edward O. Thorp.'),
  ('A World Without Email', 'Cal Newport', 2021, 'a-world-without-email', 'A World Without Email by Cal Newport.'),
  ('What Color Is Your Parachute?', 'Richard N. Bolles', 1970, 'what-color-is-your-parachute', 'What Color Is Your Parachute? by Richard N. Bolles.'),
  ('Building a Second Brain', 'Tiago Forte', 2022, 'building-a-second-brain', 'Building a Second Brain by Tiago Forte.'),
  ('Indistractable', 'Nir Eyal', 2019, 'indistractable', 'Indistractable by Nir Eyal.'),
  ('The Power of Full Engagement', 'Jim Loehr', 2003, 'the-power-of-full-engagement', 'The Power of Full Engagement by Jim Loehr.'),
  ('Hyperfocus', 'Chris Bailey', 2018, 'hyperfocus', 'Hyperfocus by Chris Bailey.'),
  ('Feel-Good Productivity', 'Ali Abdaal', 2024, 'feel-good-productivity', 'Feel-Good Productivity by Ali Abdaal.'),
  ('Supercommunicators', 'Charles Duhigg', 2024, 'supercommunicators', 'Supercommunicators by Charles Duhigg.'),
  ('Thanks for the Feedback', 'Douglas Stone', 2014, 'thanks-for-the-feedback', 'Thanks for the Feedback by Douglas Stone.'),
  ('Words That Work', 'Frank Luntz', 2007, 'words-that-work', 'Words That Work by Frank Luntz.'),
  ('TED Talks', 'Chris Anderson', 2016, 'ted-talks', 'TED Talks by Chris Anderson.'),
  ('The 5 Love Languages', 'Gary Chapman', 1992, 'the-5-love-languages', 'The 5 Love Languages by Gary Chapman.'),
  ('The Warmth of Other Suns', 'Isabel Wilkerson', 2010, 'the-warmth-of-other-suns', 'The Warmth of Other Suns by Isabel Wilkerson.'),
  ('Poverty, by America', 'Matthew Desmond', 2023, 'poverty-by-america', 'Poverty, by America by Matthew Desmond.'),
  ('Bullshit Jobs', 'David Graeber', 2018, 'bullshit-jobs', 'Bullshit Jobs by David Graeber.'),
  ('Einstein', 'Walter Isaacson', 2007, 'einstein', 'Einstein by Walter Isaacson.'),
  ('When Breath Becomes Air', 'Paul Kalanithi', 2016, 'when-breath-becomes-air', 'When Breath Becomes Air by Paul Kalanithi.'),
  ('Open', 'Andre Agassi', 2009, 'open', 'Open by Andre Agassi.'),
  ('The Diary of a Young Girl', 'Anne Frank', 1947, 'the-diary-of-a-young-girl', 'The Diary of a Young Girl by Anne Frank.'),
  ('Long Walk to Freedom', 'Nelson Mandela', 1994, 'long-walk-to-freedom', 'Long Walk to Freedom by Nelson Mandela.'),
  ('Greenlights', 'Matthew McConaughey', 2020, 'greenlights', 'Greenlights by Matthew McConaughey.'),
  ('Crying in H Mart', 'Michelle Zauner', 2021, 'crying-in-h-mart', 'Crying in H Mart by Michelle Zauner.'),
  ('The Subtle Art of Not Giving a F*ck', 'Mark Manson', 2016, 'the-subtle-art-of-not-giving-a-f-ck', 'The Subtle Art of Not Giving a F*ck by Mark Manson.'),
  ('Everything Is F*cked', 'Mark Manson', 2019, 'everything-is-f-cked', 'Everything Is F*cked by Mark Manson.'),
  ('The Four Agreements', 'Don Miguel Ruiz', 1997, 'the-four-agreements', 'The Four Agreements by Don Miguel Ruiz.'),
  ('The Power of Now', 'Eckhart Tolle', 1997, 'the-power-of-now', 'The Power of Now by Eckhart Tolle.'),
  ('12 Rules for Life', 'Jordan B. Peterson', 2018, '12-rules-for-life', '12 Rules for Life by Jordan B. Peterson.'),
  ('Build the Life You Want', 'Arthur C. Brooks', 2023, 'build-the-life-you-want', 'Build the Life You Want by Arthur C. Brooks.'),
  ('From Strength to Strength', 'Arthur C. Brooks', 2022, 'from-strength-to-strength', 'From Strength to Strength by Arthur C. Brooks.'),
  ('The Gifts of Imperfection', 'Bren\u00e9 Brown', 2010, 'the-gifts-of-imperfection', 'The Gifts of Imperfection by Bren\u00e9 Brown.'),
  ('Daring Greatly', 'Bren\u00e9 Brown', 2012, 'daring-greatly', 'Daring Greatly by Bren\u00e9 Brown.'),
  ('Atlas of the Heart', 'Bren\u00e9 Brown', 2021, 'atlas-of-the-heart', 'Atlas of the Heart by Bren\u00e9 Brown.'),
  ('The Body Is Not an Apology', 'Sonya Renee Taylor', 2018, 'the-body-is-not-an-apology', 'The Body Is Not an Apology by Sonya Renee Taylor.'),
  ('Tiny Habits', 'BJ Fogg', 2019, 'tiny-habits', 'Tiny Habits by BJ Fogg.'),
  ('The Molecule of More', 'Daniel Z. Lieberman', 2018, 'the-molecule-of-more', 'The Molecule of More by Daniel Z. Lieberman.'),
  ('Dopamine Nation', 'Anna Lembke', 2021, 'dopamine-nation', 'Dopamine Nation by Anna Lembke.'),
  ('Bittersweet', 'Susan Cain', 2022, 'bittersweet', 'Bittersweet by Susan Cain.'),
  ('The Second Mountain', 'David Brooks', 2019, 'the-second-mountain', 'The Second Mountain by David Brooks.'),
  ('How to Know a Person', 'David Brooks', 2023, 'how-to-know-a-person', 'How to Know a Person by David Brooks.'),
  ('Never Finished', 'David Goggins', 2022, 'never-finished', 'Never Finished by David Goggins.'),
  ('Discipline Is Destiny', 'Ryan Holiday', 2022, 'discipline-is-destiny', 'Discipline Is Destiny by Ryan Holiday.'),
  ('Right Thing, Right Now', 'Ryan Holiday', 2024, 'right-thing-right-now', 'Right Thing, Right Now by Ryan Holiday.'),
  ('Linchpin', 'Seth Godin', 2010, 'linchpin', 'Linchpin by Seth Godin.'),
  ('Purple Cow', 'Seth Godin', 2003, 'purple-cow', 'Purple Cow by Seth Godin.'),
  ('This Is Marketing', 'Seth Godin', 2018, 'this-is-marketing', 'This Is Marketing by Seth Godin.'),
  ('Draft No. 4', 'John McPhee', 2017, 'draft-no-4', 'Draft No. 4 by John McPhee.'),
  ('Zen in the Art of Writing', 'Ray Bradbury', 1990, 'zen-in-the-art-of-writing', 'Zen in the Art of Writing by Ray Bradbury.'),
  ('Save the Cat!', 'Blake Snyder', 2005, 'save-the-cat', 'Save the Cat! by Blake Snyder.'),
  ('Wired for Love', 'Stan Tatkin', 2011, 'wired-for-love', 'Wired for Love by Stan Tatkin.'),
  ('Boundaries', 'Henry Cloud', 1992, 'boundaries', 'Boundaries by Henry Cloud.'),
  ('Games People Play', 'Eric Berne', 1964, 'games-people-play', 'Games People Play by Eric Berne.'),
  ('Men Are from Mars, Women Are from Venus', 'John Gray', 1992, 'men-are-from-mars-women-are-from-venus', 'Men Are from Mars, Women Are from Venus by John Gray.'),
  ('Poor Charlie''s Almanack', 'Peter D. Kaufman', 2005, 'poor-charlie-s-almanack', 'Poor Charlie''s Almanack by Peter D. Kaufman.'),
  ('Mastering the Market Cycle', 'Howard Marks', 2018, 'mastering-the-market-cycle', 'Mastering the Market Cycle by Howard Marks.'),
  ('The Little Book That Beats the Market', 'Joel Greenblatt', 2005, 'the-little-book-that-beats-the-market', 'The Little Book That Beats the Market by Joel Greenblatt.'),
  ('Beating the Street', 'Peter Lynch', 1993, 'beating-the-street', 'Beating the Street by Peter Lynch.'),
  ('100 Baggers', 'Christopher W. Mayer', 2015, '100-baggers', '100 Baggers by Christopher W. Mayer.'),
  ('Devil Take the Hindmost', 'Edward Chancellor', 1999, 'devil-take-the-hindmost', 'Devil Take the Hindmost by Edward Chancellor.'),
  ('Manias, Panics, and Crashes', 'Charles P. Kindleberger', 1978, 'manias-panics-and-crashes', 'Manias, Panics, and Crashes by Charles P. Kindleberger.'),
  ('Common Sense on Mutual Funds', 'John C. Bogle', 1999, 'common-sense-on-mutual-funds', 'Common Sense on Mutual Funds by John C. Bogle.'),
  ('Genius Makers', 'Cade Metz', 2021, 'genius-makers', 'Genius Makers by Cade Metz.'),
  ('AI Superpowers', 'Kai-Fu Lee', 2018, 'ai-superpowers', 'AI Superpowers by Kai-Fu Lee.'),
  ('The Master Algorithm', 'Pedro Domingos', 2015, 'the-master-algorithm', 'The Master Algorithm by Pedro Domingos.'),
  ('The Everything Store', 'Brad Stone', 2013, 'the-everything-store', 'The Everything Store by Brad Stone.'),
  ('Hackers', 'Steven Levy', 1984, 'hackers', 'Hackers by Steven Levy.'),
  ('Running Lean', 'Ash Maurya', 2010, 'running-lean', 'Running Lean by Ash Maurya.'),
  ('Lean Analytics', 'Alistair Croll', 2013, 'lean-analytics', 'Lean Analytics by Alistair Croll.'),
  ('The Innovator''s Solution', 'Clayton M. Christensen', 2003, 'the-innovator-s-solution', 'The Innovator''s Solution by Clayton M. Christensen.'),
  ('Competing Against Luck', 'Clayton M. Christensen', 2016, 'competing-against-luck', 'Competing Against Luck by Clayton M. Christensen.'),
  ('Loonshots', 'Safi Bahcall', 2019, 'loonshots', 'Loonshots by Safi Bahcall.'),
  ('Secrets of Sand Hill Road', 'Scott Kupor', 2019, 'secrets-of-sand-hill-road', 'Secrets of Sand Hill Road by Scott Kupor.'),
  ('The Undoing Project', 'Michael Lewis', 2016, 'the-undoing-project', 'The Undoing Project by Michael Lewis.'),
  ('Liar''s Poker', 'Michael Lewis', 1989, 'liar-s-poker', 'Liar''s Poker by Michael Lewis.'),
  ('Flash Boys', 'Michael Lewis', 2014, 'flash-boys', 'Flash Boys by Michael Lewis.'),
  ('Moneyball', 'Michael Lewis', 2003, 'moneyball', 'Moneyball by Michael Lewis.'),
  ('Debt: The First 5,000 Years', 'David Graeber', 2011, 'debt-the-first-5-000-years', 'Debt: The First 5,000 Years by David Graeber.'),
  ('The Price of Tomorrow', 'Jeff Booth', 2020, 'the-price-of-tomorrow', 'The Price of Tomorrow by Jeff Booth.'),
  ('Broken Money', 'Lyn Alden', 2023, 'broken-money', 'Broken Money by Lyn Alden.'),
  ('The 4-Hour Workweek', 'Timothy Ferriss', 2007, 'the-4-hour-workweek', 'The 4-Hour Workweek by Timothy Ferriss.'),
  ('Tools of Titans', 'Timothy Ferriss', 2016, 'tools-of-titans', 'Tools of Titans by Timothy Ferriss.'),
  ('Tribe of Mentors', 'Timothy Ferriss', 2017, 'tribe-of-mentors', 'Tribe of Mentors by Timothy Ferriss.'),
  ('Free to Focus', 'Michael Hyatt', 2019, 'free-to-focus', 'Free to Focus by Michael Hyatt.'),
  ('The Bullet Journal Method', 'Ryder Carroll', 2018, 'the-bullet-journal-method', 'The Bullet Journal Method by Ryder Carroll.'),
  ('The Blue Zones', 'Dan Buettner', 2008, 'the-blue-zones', 'The Blue Zones by Dan Buettner.'),
  ('The Cure for Burnout', 'Emily Ballesteros', 2024, 'the-cure-for-burnout', 'The Cure for Burnout by Emily Ballesteros.'),
  ('Team of Teams', 'Stanley McChrystal', 2015, 'team-of-teams', 'Team of Teams by Stanley McChrystal.'),
  ('Leadership in Turbulent Times', 'Doris Kearns Goodwin', 2018, 'leadership-in-turbulent-times', 'Leadership in Turbulent Times by Doris Kearns Goodwin.'),
  ('The Making of a Manager', 'Julie Zhuo', 2019, 'the-making-of-a-manager', 'The Making of a Manager by Julie Zhuo.'),
  ('An Elegant Puzzle', 'Will Larson', 2019, 'an-elegant-puzzle', 'An Elegant Puzzle by Will Larson.'),
  ('The Manager''s Path', 'Camille Fournier', 2017, 'the-manager-s-path', 'The Manager''s Path by Camille Fournier.'),
  ('Crucial Accountability', 'Kerry Patterson', 2004, 'crucial-accountability', 'Crucial Accountability by Kerry Patterson.'),
  ('Getting to Yes', 'Roger Fisher', 1981, 'getting-to-yes', 'Getting to Yes by Roger Fisher.'),
  ('Getting Past No', 'William Ury', 1991, 'getting-past-no', 'Getting Past No by William Ury.'),
  ('Quiet Leadership', 'David Rock', 2006, 'quiet-leadership', 'Quiet Leadership by David Rock.'),
  ('Your Brain at Work', 'David Rock', 2009, 'your-brain-at-work', 'Your Brain at Work by David Rock.'),
  ('The Coaching Habit', 'Michael Bungay Stanier', 2016, 'the-coaching-habit', 'The Coaching Habit by Michael Bungay Stanier.')
on conflict (slug) do nothing;
